[package]
name = "zingo-price"
version = "0.1.0"
edition = "2024"

[dependencies]
zcash_encoding = { workspace = true }
zcash_client_backend = { workspace = true }

byteorder = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["cookies", "rustls-tls"] }
rust_decimal = "1.37.1"
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = [ "full" ] }
