[package]
name = "ffi"
version = "0.0.0"
edition = "2024"

[dependencies]
bip0039.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time", "sync"] }
uniffi = { version = "0.31", features = ["cli"] }
zcash_primitives.workspace = true

zingolib.workspace = true
pepper-sync.workspace = true
zingo_common_components = { workspace = true, features = ["for_test"] }
http.workspace = true
async-trait = "0.1.89"

[build-dependencies]
uniffi = { version = "0.31", features = ["build"] }


[lib]
# rlib is necessary to run examples
crate-type = ["rlib", "cdylib"]
name = "ffi"

[[bin]]
name = "generate-bindings"
path = "generate-bindings.rs"
