// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package ZingolibFfi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "ffi"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}
internal interface UniffiCallbackInterfaceWalletListenerMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`event`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
@Structure.FieldOrder("uniffiFree", "uniffiClone", "onEvent")
internal open class UniffiVTableCallbackInterfaceWalletListener(
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    @JvmField internal var `uniffiClone`: UniffiCallbackInterfaceClone? = null,
    @JvmField internal var `onEvent`: UniffiCallbackInterfaceWalletListenerMethod0? = null,
) : Structure() {
    class UniffiByValue(
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
        `uniffiClone`: UniffiCallbackInterfaceClone? = null,
        `onEvent`: UniffiCallbackInterfaceWalletListenerMethod0? = null,
    ): UniffiVTableCallbackInterfaceWalletListener(`uniffiFree`,`uniffiClone`,`onEvent`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceWalletListener) {
        `uniffiFree` = other.`uniffiFree`
        `uniffiClone` = other.`uniffiClone`
        `onEvent` = other.`onEvent`
    }

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "ffi"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_ffi_checksum_method_walletengine_clear_listener(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_get_balance_snapshot(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_get_network_height(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_init_from_seed(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_init_from_ufvk(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_init_new(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_pause_sync(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_set_listener(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_shutdown(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_start_sync(
    ): Short
    external fun uniffi_ffi_checksum_method_walletengine_unload_wallet(
    ): Short
    external fun uniffi_ffi_checksum_constructor_walletengine_new(
    ): Short
    external fun uniffi_ffi_checksum_method_walletlistener_on_event(
    ): Short
    external fun ffi_ffi_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    
    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "ffi"))
        uniffiCallbackInterfaceWalletListener.register(this)
        
    }
    external fun uniffi_ffi_fn_clone_walletengine(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_ffi_fn_free_walletengine(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_constructor_walletengine_new(uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_ffi_fn_method_walletengine_clear_listener(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_method_walletengine_get_balance_snapshot(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_ffi_fn_method_walletengine_get_network_height(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun uniffi_ffi_fn_method_walletengine_init_from_seed(`ptr`: Long,`params`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_method_walletengine_init_from_ufvk(`ptr`: Long,`params`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_method_walletengine_init_new(`ptr`: Long,`indexerUri`: RustBuffer.ByValue,`chain`: RustBuffer.ByValue,`perf`: RustBuffer.ByValue,`minconf`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_method_walletengine_pause_sync(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_method_walletengine_set_listener(`ptr`: Long,`listener`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_method_walletengine_shutdown(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_method_walletengine_start_sync(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_method_walletengine_unload_wallet(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_ffi_fn_init_callback_vtable_walletlistener(`vtable`: UniffiVTableCallbackInterfaceWalletListener,
    ): Unit
    external fun ffi_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_ffi_checksum_method_walletengine_clear_listener() != 49071.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_get_balance_snapshot() != 33695.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_get_network_height() != 50577.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_init_from_seed() != 23959.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_init_from_ufvk() != 15742.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_init_new() != 6760.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_pause_sync() != 34131.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_set_listener() != 31906.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_shutdown() != 16655.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_start_sync() != 23964.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletengine_unload_wallet() != 57698.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_constructor_walletengine_new() != 12055.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ffi_checksum_method_walletlistener_on_event() != 26795.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0
// Callback return codes
internal const val UNIFFI_CALLBACK_SUCCESS = 0
internal const val UNIFFI_CALLBACK_ERROR = 1
internal const val UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

/**
 * @suppress
 */
public abstract class FfiConverterCallbackInterface<CallbackInterface: Any>: FfiConverter<CallbackInterface, Long> {
    internal val handleMap = UniffiHandleMap<CallbackInterface>()

    internal fun drop(handle: Long) {
        handleMap.remove(handle)
    }

    override fun lift(value: Long): CallbackInterface {
        return handleMap.get(value)
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) = handleMap.insert(value)

    override fun allocationSize(value: CallbackInterface) = 8UL

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


public interface WalletEngineInterface {
    
    /**
     * Clears the currently installed listener, if any.
     *
     * After calling this, no further [`WalletEvent`] callbacks will be delivered until a new
     * listener is set via [`WalletEngine::set_listener`].
     *
     * ## Errors
     * Returns [`WalletError::ListenerLockPoisoned`] if the listener mutex is poisoned.
     */
    fun `clearListener`()
    
    /**
     * Returns a snapshot of the wallet balance for Account 0.
     *
     * The returned [`BalanceSnapshot`] is a simplified, FFI-stable view derived from the
     * underlying zingolib [`AccountBalance`] type.
     *
     * This method is **blocking**. The balance query runs on the engine thread and the result
     * is returned via a oneshot reply channel.
     *
     * ## Errors
     * - [`WalletError::NotInitialized`] if no wallet has been initialized.
     * - [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * - [`WalletError::Internal`] if the underlying balance query fails.
     */
    fun `getBalanceSnapshot`(): BalanceSnapshot
    
    /**
     * Returns the latest known network height from the configured indexer.
     *
     * This is a gRPC call to the indexer (`get_latest_block`) and is useful for:
     * - UI display (“current tip”)
     * - tests that need to observe tip movement independently of sync progress
     *
     * This method is **blocking**. The gRPC call runs on the engine thread and the result is returned
     * via a oneshot reply channel.
     *
     * ## Errors
     * - [`WalletError::NotInitialized`] if no indexer has been configured yet.
     * - [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * - [`WalletError::Internal`] if the indexer gRPC fails.
     */
    fun `getNetworkHeight`(): kotlin.UInt
    
    /**
     * Initializes a wallet from a seed phrase and explicit birthday height.
     *
     * This is the entrypoint for restoring from seed. It:
     * - Builds a [`ZingoConfig`] from the provided parameters.
     * - Parses the BIP39 mnemonic from `seed_phrase`.
     * - Constructs a [`LightWallet`] using the provided `birthday`.
     * - Creates a [`LightClient`] from that wallet, replacing any previously loaded wallet.
     *
     * This method is **blocking** by design (FFI-friendly). The async work is performed on the
     * engine thread and the result is returned via a oneshot reply channel.
     *
     * ## Parameters
     * - `seed_phrase`: BIP39 mnemonic words separated by spaces
     * - `birthday`: wallet birthday (starting scan height)
     * - `indexer_uri`: lightwalletd URI
     * - `chain`: chain selection (mainnet/testnet/regtest)
     * - `perf`: sync performance preset
     * - `minconf`: minimum confirmations for spendable funds. Must be >= 1.
     *
     * ## Events
     * Does not automatically start syncing. Call [`WalletEngine::start_sync`] to begin a sync round.
     *
     * ## Errors
     * - [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * - [`WalletError::Internal`] on config/mnemonic/wallet construction errors.
     */
    fun `initFromSeed`(`params`: RestoreParams)
    
    fun `initFromUfvk`(`params`: UfvkImportParams)
    
    /**
     * Initializes a brand-new wallet on the engine thread.
     *
     * This is the entrypoint for new wallets. It:
     * - Builds a [`ZingoConfig`] from the provided parameters.
     * - Queries the indexer for the latest block height to derive a conservative birthday.
     * - Constructs a new [`LightClient`], replacing any previously loaded wallet.
     *
     * This method is **blocking** by design. The async work is performed on the
     * engine thread and the result is returned via a oneshot reply channel.
     *
     * ## Parameters
     * - `indexer_uri`: zainod/lightwalletd URI, e.g. `http://localhost:9067`
     * - `chain`: chain selection (mainnet/testnet/regtest)
     * - `perf`: sync performance preset
     * - `minconf`: minimum confirmations for spendable funds. Must be >= 1.
     *
     * ## Events
     * Does not automatically start syncing. Call [`WalletEngine::start_sync`] to begin a sync round.
     *
     * ## Errors
     * - [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * - [`WalletError::Internal`] on config/build errors or indexer gRPC failures.
     */
    fun `initNew`(`indexerUri`: kotlin.String, `chain`: Chain, `perf`: Performance, `minconf`: kotlin.UInt)
    
    /**
     * Requests that an in-progress sync pause.
     *
     * This calls into zingolib's pause mechanism. If successful, the engine emits
     * [`WalletEvent::SyncPaused`].
     *
     * Note: pausing is best-effort. If no wallet exists, an async [`WalletEvent::Error`] is emitted
     * with `code="pause_sync_failed"`.
     *
     * ## Errors
     * Returns [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     */
    fun `pauseSync`()
    
    /**
     * Installs a listener that receives asynchronous [`WalletEvent`] callbacks.
     *
     * The listener is invoked from the engine thread. Implementations must be:
     * - thread-safe (`Send + Sync`)
     * - fast / non-blocking (heavy work should be offloaded by the caller)
     *
     * If the listener panics, the engine catches the panic to avoid crashing the engine thread.
     *
     * Replaces any previously installed listener.
     *
     * ## Errors
     * Returns [`WalletError::ListenerLockPoisoned`] if the listener mutex is poisoned.
     */
    fun `setListener`(`listener`: WalletListener)
    
    /**
     * Shuts down the engine thread.
     *
     * This sends a shutdown command to the engine loop. After shutdown:
     * - all subsequent method calls that require the engine thread will typically fail with
     * [`WalletError::CommandQueueClosed`]
     * - no further [`WalletEvent`] callbacks will be delivered
     *
     * Shutdown is best-effort; the command is queued if possible.
     *
     * ## Errors
     * Returns [`WalletError::CommandQueueClosed`] if the command queue is already closed.
     */
    fun `shutdown`()
    
    /**
     * Starts a **single manual sync round**.
     *
     * The sync round runs on the engine thread and emits events:
     * - [`WalletEvent::SyncStarted`] immediately when accepted
     * - repeated [`WalletEvent::SyncProgress`] updates while syncing
     * - optional [`WalletEvent::BalanceChanged`] updates when balance changes
     * - [`WalletEvent::SyncFinished`] once the sync completes successfully
     * - [`WalletEvent::Error`] if the sync fails
     *
     * ## Manual model
     * This method performs **one** round per invocation. It does not “follow” the chain forever.
     * If the network tip advances later and you want to catch up again, call `start_sync()` again.
     *
     * ## Reentrancy
     * If a sync is already running, additional `start_sync()` calls are ignored.
     *
     * ## Errors
     * Returns [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * If the wallet is not initialized, an async [`WalletEvent::Error`] is emitted with
     * `code="start_sync_failed"`.
     */
    fun `startSync`()
    
    /**
     * Shuts down the engine thread and unloads the wallet from memory.
     */
    fun `unloadWallet`()
    
    companion object
}

open class WalletEngine: Disposable, AutoCloseable, WalletEngineInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }
    /**
     * Creates a new [`WalletEngine`] and starts the internal engine thread.
     *
     * This constructor:
     * - Allocates a command queue used to communicate with the engine thread.
     * - Spawns a dedicated OS thread that owns a Tokio runtime and all async wallet state, through the [`LightClient`].
     * - Emits [`WalletEvent::EngineReady`] once the engine thread is running.
     *
     * ## Threading / FFI design
     * All UniFFI-exposed methods on [`WalletEngine`] are *synchronous* and safe to call from
     * Swift/Kotlin. Any async work is executed on the engine thread.
     *
     * ## Errors
     * Returns [`WalletError`] if the engine cannot be created.
     */
    constructor() :
        this(UniffiWithHandle, 
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_constructor_walletengine_new(
    
        _status)
}
    )

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_ffi_fn_free_walletengine(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_ffi_fn_clone_walletengine(handle, status)
        }
    }

    
    /**
     * Clears the currently installed listener, if any.
     *
     * After calling this, no further [`WalletEvent`] callbacks will be delivered until a new
     * listener is set via [`WalletEngine::set_listener`].
     *
     * ## Errors
     * Returns [`WalletError::ListenerLockPoisoned`] if the listener mutex is poisoned.
     */
    @Throws(WalletException::class)override fun `clearListener`()
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_clear_listener(
        it,
        _status)
}
    }
    
    

    
    /**
     * Returns a snapshot of the wallet balance for Account 0.
     *
     * The returned [`BalanceSnapshot`] is a simplified, FFI-stable view derived from the
     * underlying zingolib [`AccountBalance`] type.
     *
     * This method is **blocking**. The balance query runs on the engine thread and the result
     * is returned via a oneshot reply channel.
     *
     * ## Errors
     * - [`WalletError::NotInitialized`] if no wallet has been initialized.
     * - [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * - [`WalletError::Internal`] if the underlying balance query fails.
     */
    @Throws(WalletException::class)override fun `getBalanceSnapshot`(): BalanceSnapshot {
            return FfiConverterTypeBalanceSnapshot.lift(
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_get_balance_snapshot(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Returns the latest known network height from the configured indexer.
     *
     * This is a gRPC call to the indexer (`get_latest_block`) and is useful for:
     * - UI display (“current tip”)
     * - tests that need to observe tip movement independently of sync progress
     *
     * This method is **blocking**. The gRPC call runs on the engine thread and the result is returned
     * via a oneshot reply channel.
     *
     * ## Errors
     * - [`WalletError::NotInitialized`] if no indexer has been configured yet.
     * - [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * - [`WalletError::Internal`] if the indexer gRPC fails.
     */
    @Throws(WalletException::class)override fun `getNetworkHeight`(): kotlin.UInt {
            return FfiConverterUInt.lift(
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_get_network_height(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Initializes a wallet from a seed phrase and explicit birthday height.
     *
     * This is the entrypoint for restoring from seed. It:
     * - Builds a [`ZingoConfig`] from the provided parameters.
     * - Parses the BIP39 mnemonic from `seed_phrase`.
     * - Constructs a [`LightWallet`] using the provided `birthday`.
     * - Creates a [`LightClient`] from that wallet, replacing any previously loaded wallet.
     *
     * This method is **blocking** by design (FFI-friendly). The async work is performed on the
     * engine thread and the result is returned via a oneshot reply channel.
     *
     * ## Parameters
     * - `seed_phrase`: BIP39 mnemonic words separated by spaces
     * - `birthday`: wallet birthday (starting scan height)
     * - `indexer_uri`: lightwalletd URI
     * - `chain`: chain selection (mainnet/testnet/regtest)
     * - `perf`: sync performance preset
     * - `minconf`: minimum confirmations for spendable funds. Must be >= 1.
     *
     * ## Events
     * Does not automatically start syncing. Call [`WalletEngine::start_sync`] to begin a sync round.
     *
     * ## Errors
     * - [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * - [`WalletError::Internal`] on config/mnemonic/wallet construction errors.
     */
    @Throws(WalletException::class)override fun `initFromSeed`(`params`: RestoreParams)
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_init_from_seed(
        it,
        FfiConverterTypeRestoreParams.lower(`params`),_status)
}
    }
    
    

    
    @Throws(WalletException::class)override fun `initFromUfvk`(`params`: UfvkImportParams)
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_init_from_ufvk(
        it,
        FfiConverterTypeUFVKImportParams.lower(`params`),_status)
}
    }
    
    

    
    /**
     * Initializes a brand-new wallet on the engine thread.
     *
     * This is the entrypoint for new wallets. It:
     * - Builds a [`ZingoConfig`] from the provided parameters.
     * - Queries the indexer for the latest block height to derive a conservative birthday.
     * - Constructs a new [`LightClient`], replacing any previously loaded wallet.
     *
     * This method is **blocking** by design. The async work is performed on the
     * engine thread and the result is returned via a oneshot reply channel.
     *
     * ## Parameters
     * - `indexer_uri`: zainod/lightwalletd URI, e.g. `http://localhost:9067`
     * - `chain`: chain selection (mainnet/testnet/regtest)
     * - `perf`: sync performance preset
     * - `minconf`: minimum confirmations for spendable funds. Must be >= 1.
     *
     * ## Events
     * Does not automatically start syncing. Call [`WalletEngine::start_sync`] to begin a sync round.
     *
     * ## Errors
     * - [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * - [`WalletError::Internal`] on config/build errors or indexer gRPC failures.
     */
    @Throws(WalletException::class)override fun `initNew`(`indexerUri`: kotlin.String, `chain`: Chain, `perf`: Performance, `minconf`: kotlin.UInt)
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_init_new(
        it,
        FfiConverterString.lower(`indexerUri`),FfiConverterTypeChain.lower(`chain`),FfiConverterTypePerformance.lower(`perf`),FfiConverterUInt.lower(`minconf`),_status)
}
    }
    
    

    
    /**
     * Requests that an in-progress sync pause.
     *
     * This calls into zingolib's pause mechanism. If successful, the engine emits
     * [`WalletEvent::SyncPaused`].
     *
     * Note: pausing is best-effort. If no wallet exists, an async [`WalletEvent::Error`] is emitted
     * with `code="pause_sync_failed"`.
     *
     * ## Errors
     * Returns [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     */
    @Throws(WalletException::class)override fun `pauseSync`()
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_pause_sync(
        it,
        _status)
}
    }
    
    

    
    /**
     * Installs a listener that receives asynchronous [`WalletEvent`] callbacks.
     *
     * The listener is invoked from the engine thread. Implementations must be:
     * - thread-safe (`Send + Sync`)
     * - fast / non-blocking (heavy work should be offloaded by the caller)
     *
     * If the listener panics, the engine catches the panic to avoid crashing the engine thread.
     *
     * Replaces any previously installed listener.
     *
     * ## Errors
     * Returns [`WalletError::ListenerLockPoisoned`] if the listener mutex is poisoned.
     */
    @Throws(WalletException::class)override fun `setListener`(`listener`: WalletListener)
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_set_listener(
        it,
        FfiConverterTypeWalletListener.lower(`listener`),_status)
}
    }
    
    

    
    /**
     * Shuts down the engine thread.
     *
     * This sends a shutdown command to the engine loop. After shutdown:
     * - all subsequent method calls that require the engine thread will typically fail with
     * [`WalletError::CommandQueueClosed`]
     * - no further [`WalletEvent`] callbacks will be delivered
     *
     * Shutdown is best-effort; the command is queued if possible.
     *
     * ## Errors
     * Returns [`WalletError::CommandQueueClosed`] if the command queue is already closed.
     */
    @Throws(WalletException::class)override fun `shutdown`()
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_shutdown(
        it,
        _status)
}
    }
    
    

    
    /**
     * Starts a **single manual sync round**.
     *
     * The sync round runs on the engine thread and emits events:
     * - [`WalletEvent::SyncStarted`] immediately when accepted
     * - repeated [`WalletEvent::SyncProgress`] updates while syncing
     * - optional [`WalletEvent::BalanceChanged`] updates when balance changes
     * - [`WalletEvent::SyncFinished`] once the sync completes successfully
     * - [`WalletEvent::Error`] if the sync fails
     *
     * ## Manual model
     * This method performs **one** round per invocation. It does not “follow” the chain forever.
     * If the network tip advances later and you want to catch up again, call `start_sync()` again.
     *
     * ## Reentrancy
     * If a sync is already running, additional `start_sync()` calls are ignored.
     *
     * ## Errors
     * Returns [`WalletError::CommandQueueClosed`] if the engine thread has exited.
     * If the wallet is not initialized, an async [`WalletEvent::Error`] is emitted with
     * `code="start_sync_failed"`.
     */
    @Throws(WalletException::class)override fun `startSync`()
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_start_sync(
        it,
        _status)
}
    }
    
    

    
    /**
     * Shuts down the engine thread and unloads the wallet from memory.
     */
    @Throws(WalletException::class)override fun `unloadWallet`()
        = 
    callWithHandle {
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_ffi_fn_method_walletengine_unload_wallet(
        it,
        _status)
}
    }
    
    

    

    


    
    
    /**
     * @suppress
     */
    companion object
    
}


/**
 * @suppress
 */
public object FfiConverterTypeWalletEngine: FfiConverter<WalletEngine, Long> {
    override fun lower(value: WalletEngine): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): WalletEngine {
        return WalletEngine(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): WalletEngine {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: WalletEngine) = 8UL

    override fun write(value: WalletEngine, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}



data class BalanceSnapshot (
    var `confirmed`: kotlin.String
    , 
    var `total`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBalanceSnapshot: FfiConverterRustBuffer<BalanceSnapshot> {
    override fun read(buf: ByteBuffer): BalanceSnapshot {
        return BalanceSnapshot(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: BalanceSnapshot) = (
            FfiConverterString.allocationSize(value.`confirmed`) +
            FfiConverterString.allocationSize(value.`total`)
    )

    override fun write(value: BalanceSnapshot, buf: ByteBuffer) {
            FfiConverterString.write(value.`confirmed`, buf)
            FfiConverterString.write(value.`total`, buf)
    }
}



data class RestoreParams (
    var `seedPhrase`: SeedPhrase
    , 
    var `birthday`: kotlin.UInt
    , 
    var `indexerUri`: kotlin.String
    , 
    var `chain`: Chain
    , 
    var `perf`: Performance
    , 
    var `minconf`: kotlin.UInt
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRestoreParams: FfiConverterRustBuffer<RestoreParams> {
    override fun read(buf: ByteBuffer): RestoreParams {
        return RestoreParams(
            FfiConverterTypeSeedPhrase.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeChain.read(buf),
            FfiConverterTypePerformance.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: RestoreParams) = (
            FfiConverterTypeSeedPhrase.allocationSize(value.`seedPhrase`) +
            FfiConverterUInt.allocationSize(value.`birthday`) +
            FfiConverterString.allocationSize(value.`indexerUri`) +
            FfiConverterTypeChain.allocationSize(value.`chain`) +
            FfiConverterTypePerformance.allocationSize(value.`perf`) +
            FfiConverterUInt.allocationSize(value.`minconf`)
    )

    override fun write(value: RestoreParams, buf: ByteBuffer) {
            FfiConverterTypeSeedPhrase.write(value.`seedPhrase`, buf)
            FfiConverterUInt.write(value.`birthday`, buf)
            FfiConverterString.write(value.`indexerUri`, buf)
            FfiConverterTypeChain.write(value.`chain`, buf)
            FfiConverterTypePerformance.write(value.`perf`, buf)
            FfiConverterUInt.write(value.`minconf`, buf)
    }
}



data class SeedPhrase (
    var `words`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSeedPhrase: FfiConverterRustBuffer<SeedPhrase> {
    override fun read(buf: ByteBuffer): SeedPhrase {
        return SeedPhrase(
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: SeedPhrase) = (
            FfiConverterString.allocationSize(value.`words`)
    )

    override fun write(value: SeedPhrase, buf: ByteBuffer) {
            FfiConverterString.write(value.`words`, buf)
    }
}



data class UfvkImportParams (
    var `ufvk`: kotlin.String
    , 
    var `birthday`: kotlin.UInt
    , 
    var `indexerUri`: kotlin.String
    , 
    var `chain`: Chain
    , 
    var `perf`: Performance
    , 
    var `minconf`: kotlin.UInt
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeUFVKImportParams: FfiConverterRustBuffer<UfvkImportParams> {
    override fun read(buf: ByteBuffer): UfvkImportParams {
        return UfvkImportParams(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeChain.read(buf),
            FfiConverterTypePerformance.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: UfvkImportParams) = (
            FfiConverterString.allocationSize(value.`ufvk`) +
            FfiConverterUInt.allocationSize(value.`birthday`) +
            FfiConverterString.allocationSize(value.`indexerUri`) +
            FfiConverterTypeChain.allocationSize(value.`chain`) +
            FfiConverterTypePerformance.allocationSize(value.`perf`) +
            FfiConverterUInt.allocationSize(value.`minconf`)
    )

    override fun write(value: UfvkImportParams, buf: ByteBuffer) {
            FfiConverterString.write(value.`ufvk`, buf)
            FfiConverterUInt.write(value.`birthday`, buf)
            FfiConverterString.write(value.`indexerUri`, buf)
            FfiConverterTypeChain.write(value.`chain`, buf)
            FfiConverterTypePerformance.write(value.`perf`, buf)
            FfiConverterUInt.write(value.`minconf`, buf)
    }
}




enum class Chain {
    
    MAINNET,
    TESTNET,
    REGTEST;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeChain: FfiConverterRustBuffer<Chain> {
    override fun read(buf: ByteBuffer) = try {
        Chain.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Chain) = 4UL

    override fun write(value: Chain, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Performance {
    
    MAXIMUM,
    HIGH,
    MEDIUM,
    LOW;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypePerformance: FfiConverterRustBuffer<Performance> {
    override fun read(buf: ByteBuffer) = try {
        Performance.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Performance) = 4UL

    override fun write(value: Performance, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class WalletException: kotlin.Exception() {
    
    class CommandQueueClosed(
        ) : WalletException() {
        override val message
            get() = ""
    }
    
    class ListenerLockPoisoned(
        ) : WalletException() {
        override val message
            get() = ""
    }
    
    class NotInitialized(
        ) : WalletException() {
        override val message
            get() = ""
    }
    
    class Internal(
        
        val v1: kotlin.String
        ) : WalletException() {
        override val message
            get() = "v1=${ v1 }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<WalletException> {
        override fun lift(error_buf: RustBuffer.ByValue): WalletException = FfiConverterTypeWalletError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeWalletError : FfiConverterRustBuffer<WalletException> {
    override fun read(buf: ByteBuffer): WalletException {
        

        return when(buf.getInt()) {
            1 -> WalletException.CommandQueueClosed()
            2 -> WalletException.ListenerLockPoisoned()
            3 -> WalletException.NotInitialized()
            4 -> WalletException.Internal(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: WalletException): ULong {
        return when(value) {
            is WalletException.CommandQueueClosed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is WalletException.ListenerLockPoisoned -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is WalletException.NotInitialized -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is WalletException.Internal -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: WalletException, buf: ByteBuffer) {
        when(value) {
            is WalletException.CommandQueueClosed -> {
                buf.putInt(1)
                Unit
            }
            is WalletException.ListenerLockPoisoned -> {
                buf.putInt(2)
                Unit
            }
            is WalletException.NotInitialized -> {
                buf.putInt(3)
                Unit
            }
            is WalletException.Internal -> {
                buf.putInt(4)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}



sealed class WalletEvent {
    
    object EngineReady : WalletEvent()
    
    
    object SyncStarted : WalletEvent()
    
    
    data class SyncProgress(
        val `walletHeight`: kotlin.UInt, 
        val `networkHeight`: kotlin.UInt, 
        val `percent`: kotlin.Float) : WalletEvent()
        
    {
        

        companion object
    }
    
    object SyncPaused : WalletEvent()
    
    
    object SyncFinished : WalletEvent()
    
    
    data class BalanceChanged(
        val v1: ZingolibFfi.BalanceSnapshot) : WalletEvent()
        
    {
        

        companion object
    }
    
    data class Error(
        val `code`: kotlin.String, 
        val `message`: kotlin.String) : WalletEvent()
        
    {
        

        companion object
    }
    
    object Unloaded : WalletEvent()
    
    

    

    
    


    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeWalletEvent : FfiConverterRustBuffer<WalletEvent>{
    override fun read(buf: ByteBuffer): WalletEvent {
        return when(buf.getInt()) {
            1 -> WalletEvent.EngineReady
            2 -> WalletEvent.SyncStarted
            3 -> WalletEvent.SyncProgress(
                FfiConverterUInt.read(buf),
                FfiConverterUInt.read(buf),
                FfiConverterFloat.read(buf),
                )
            4 -> WalletEvent.SyncPaused
            5 -> WalletEvent.SyncFinished
            6 -> WalletEvent.BalanceChanged(
                FfiConverterTypeBalanceSnapshot.read(buf),
                )
            7 -> WalletEvent.Error(
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                )
            8 -> WalletEvent.Unloaded
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: WalletEvent) = when(value) {
        is WalletEvent.EngineReady -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
        is WalletEvent.SyncStarted -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
        is WalletEvent.SyncProgress -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterUInt.allocationSize(value.`walletHeight`)
                + FfiConverterUInt.allocationSize(value.`networkHeight`)
                + FfiConverterFloat.allocationSize(value.`percent`)
            )
        }
        is WalletEvent.SyncPaused -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
        is WalletEvent.SyncFinished -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
        is WalletEvent.BalanceChanged -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeBalanceSnapshot.allocationSize(value.v1)
            )
        }
        is WalletEvent.Error -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`code`)
                + FfiConverterString.allocationSize(value.`message`)
            )
        }
        is WalletEvent.Unloaded -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
            )
        }
    }

    override fun write(value: WalletEvent, buf: ByteBuffer) {
        when(value) {
            is WalletEvent.EngineReady -> {
                buf.putInt(1)
                Unit
            }
            is WalletEvent.SyncStarted -> {
                buf.putInt(2)
                Unit
            }
            is WalletEvent.SyncProgress -> {
                buf.putInt(3)
                FfiConverterUInt.write(value.`walletHeight`, buf)
                FfiConverterUInt.write(value.`networkHeight`, buf)
                FfiConverterFloat.write(value.`percent`, buf)
                Unit
            }
            is WalletEvent.SyncPaused -> {
                buf.putInt(4)
                Unit
            }
            is WalletEvent.SyncFinished -> {
                buf.putInt(5)
                Unit
            }
            is WalletEvent.BalanceChanged -> {
                buf.putInt(6)
                FfiConverterTypeBalanceSnapshot.write(value.v1, buf)
                Unit
            }
            is WalletEvent.Error -> {
                buf.putInt(7)
                FfiConverterString.write(value.`code`, buf)
                FfiConverterString.write(value.`message`, buf)
                Unit
            }
            is WalletEvent.Unloaded -> {
                buf.putInt(8)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}







public interface WalletListener {
    
    fun `onEvent`(`event`: WalletEvent)
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceWalletListener {
    internal object `onEvent`: UniffiCallbackInterfaceWalletListenerMethod0 {
        override fun callback(`uniffiHandle`: Long,`event`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeWalletListener.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onEvent`(
                    FfiConverterTypeWalletEvent.lift(`event`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeWalletListener.handleMap.remove(handle)
        }
    }

    internal object uniffiClone: UniffiCallbackInterfaceClone {
        override fun callback(handle: Long): Long {
            return FfiConverterTypeWalletListener.handleMap.clone(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceWalletListener.UniffiByValue(
        uniffiFree,
        uniffiClone,
        `onEvent`,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_ffi_fn_init_callback_vtable_walletlistener(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeWalletListener: FfiConverterCallbackInterface<WalletListener>()

