[package]
name = "libtonode-tests"
version = "0.2.0"
edition = "2024"
publish = false

[features]
proptests = []
chain_generic_tests = []
ci = ["zingolib/ci"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
zingolib = { workspace = true, features = ["testutils"] }
zingo-status = { workspace = true }
pepper-sync = { workspace = true }
zingo_common_components = { workspace = true, features = ["for_test"] }

zip32 = { workspace = true }
zcash_address = { workspace = true, features = ["test-dependencies"] }
zcash_client_backend = { workspace = true }
zcash_primitives = { workspace = true }
zcash_protocol = { workspace = true }

bip0039.workspace = true

tokio = { workspace = true, features = ["full"] }
json = { workspace = true }
itertools = { workspace = true }
proptest.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zebra-chain = { git = "https://github.com/zingolabs/zebra.git" , rev = "1168a2f391a17f3ccab65a095d9219b7455d0fea" }

http = { workspace = true }

[dev-dependencies]
rustls.workspace = true
