[package]
name = "libtonode-tests"
version = "0.2.0"
edition = "2024"

[features]
chain_generic_tests = []
ci = ["zingolib/ci"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
zingolib = { workspace = true, features = ["test-elevation"] }
zingo-status = { workspace = true }
pepper-sync = { workspace = true }
testvectors = { workspace = true }

zcash_services = { workspace = true }

zip32 = { workspace = true }
zcash_address = { workspace = true, features = ["test-dependencies"] }
zcash_client_backend = { workspace = true }
zcash_primitives = { workspace = true }
zcash_protocol = { workspace = true }

bip0039.workspace = true

tokio = { workspace = true, features = ["full"] }
json = { workspace = true }
itertools = { workspace = true }
tempfile.workspace = true
proptest.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
rustls.workspace = true
