[package]
name = "darkside-tests"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
chain_generic_tests = []

[dependencies]
zingolib = { workspace = true, features = ["darkside_tests"] }
zingo-netutils = { workspace = true }
testvectors = { workspace = true }

orchard = { workspace = true }
sapling-crypto = { workspace = true }
incrementalmerkletree = { workspace = true }
zcash_primitives = { workspace = true }
zcash_protocol = { workspace = true }

tokio = { workspace = true, features = ["full"] }
http = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tower = { workspace = true }
hex = { workspace = true }
tempfile = { workspace = true }
portpicker = { workspace = true }
futures-util = { workspace = true }
serde_json = { workspace = true }
proptest = { workspace = true }

# Logging
tracing-subscriber.workspace = true

[build-dependencies]
tonic-build = { workspace = true }
