[package]
name = "zingo_wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
zingolib = { workspace = true }
pepper-sync.workspace = true

zcash_wallet_interface = { git = "file:///home/cupress/ZINGO/zcash_wallet_interface", branch = "dev" }

zingo_netutils.workspace = true
zingo_common_components.workspace = true

bip0039.workspace = true
zcash_client_backend.workspace = true
zcash_primitives.workspace = true

tonic.workspace = true
http.workspace = true
rustls.workspace = true

thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
zingo_test_vectors = { git = "https://github.com/zingolabs/infrastructure.git", branch = "dev" }
