use super::super::LightWallet;

/// ExampleWalletNetworkCase sorts first by Network, then seed, then last saved version.
/// It is public so that any consumer can select and load any example wallet.
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleWalletNetwork {
    /// /
    Regtest(ExampleRegtestWalletSeed),
    /// /
    Testnet(ExampleTestnetWalletSeed),
    /// /
    Mainnet(ExampleMainnetWalletSeed),
}

/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleMainnetWalletSeed {
    /// this is a mainnet wallet originally called missing_data_test
    VTFCORFBCBPCTCFUPMEGMWBP(ExampleVTFCORFBCBPCTCFUPMEGMWBPVersion),
    /// empty mainnet wallet
    HHCCLALTPCCKCSSLPCNETBLR(ExampleHHCCLALTPCCKCSSLPCNETBLRVersion),
}
/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleVTFCORFBCBPCTCFUPMEGMWBPVersion {
    /// wallet was last saved in this serialization version
    V28,
}
/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleHHCCLALTPCCKCSSLPCNETBLRVersion {
    /// wallet was last saved in this serialization version
    Gf0aaf9347,
}
/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleTestnetWalletSeed {
    /// this testnet wallet was generated at the beginning of serialization v28 by fluidvanadium
    CBBHRWIILGBRABABSSHSMTPR(ExampleCBBHRWIILGBRABABSSHSMTPRVersion),
    /// This is a testnet seed, generated by fluidvanadium at the beginning of owls (this example wallet enumeration)
    MSKMGDBHOTBPETCJWCSPGOPP(ExampleMSKMGDBHOTBPETCJWCSPGOPPVersion),
}
/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleMSKMGDBHOTBPETCJWCSPGOPPVersion {
    /// wallet was last saved by the code in this commit
    Gab72a38b,
    /// this wallet was synced in this version. does it have a bunch of taz scattered around different addresses?
    G93738061a,
    /// NU6 added to zingolib re-allows testnet tests by this commit
    Ga74fed621,
}
/// A testnet wallet initiated with
/// --seed "chimney better bulb horror rebuild whisper improve intact letter giraffe brave rib appear bulk aim burst snap salt hill sad merge tennis phrase raise"
/// with 3 addresses containing all receivers.
/// including orchard and sapling transactions
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleCBBHRWIILGBRABABSSHSMTPRVersion {
    /// wallet was last saved in this serialization version
    V26,
    /// wallet was last saved in this serialization version
    V27,
    /// wallet was last saved in this serialization version
    V28,
    /// wallet was last saved at this commit
    G2f3830058,
}
/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleRegtestWalletSeed {
    /// this is a regtest wallet originally called old_wallet_reorg_test_wallet
    HMVASMUVWMSSVICHCARBPOCT(ExampleHMVASMUVWMSSVICHCARBPOCTVersion),
    /// this is a regtest wallet originally called v26/sap_only
    AAAAAAAAAAAAAAAAAAAAAAAA(ExampleAAAAAAAAAAAAAAAAAAAAAAAAVersion),
    /// another regtest wallet
    AADAALACAADAALACAADAALAC(ExampleAADAALACAADAALACAADAALACVersion),
}
/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleHMVASMUVWMSSVICHCARBPOCTVersion {
    /// wallet was last saved in this serialization version
    V27,
}
/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleAAAAAAAAAAAAAAAAAAAAAAAAVersion {
    /// wallet was last saved in this serialization version
    V26,
}
/// /
#[non_exhaustive]
#[derive(Clone)]
pub enum ExampleAADAALACAADAALACAADAALACVersion {
    /// existing receivers?
    OrchAndSapl,
    /// existing receivers?
    OrchOnly,
}

impl ExampleWalletNetwork {
    /// loads test wallets
    /// this function can be improved by a macro. even better would be to derive directly from the enum.
    /// loads any one of the test wallets included in the examples
    pub async fn load_example_wallet(&self) -> LightWallet {
        match self {
            ExampleWalletNetwork::Regtest(ExampleRegtestWalletSeed::HMVASMUVWMSSVICHCARBPOCT(
                ExampleHMVASMUVWMSSVICHCARBPOCTVersion::V27,
            )) => {
                LightWallet::unsafe_from_buffer_regtest(include_bytes!(
                    "examples/regtest/hmvasmuvwmssvichcarbpoct/v27/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Regtest(ExampleRegtestWalletSeed::AAAAAAAAAAAAAAAAAAAAAAAA(
                ExampleAAAAAAAAAAAAAAAAAAAAAAAAVersion::V26,
            )) => {
                LightWallet::unsafe_from_buffer_regtest(include_bytes!(
                    "examples/regtest/aaaaaaaaaaaaaaaaaaaaaaaa/v26/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Regtest(ExampleRegtestWalletSeed::AADAALACAADAALACAADAALAC(
                ExampleAADAALACAADAALACAADAALACVersion::OrchAndSapl,
            )) => {
                LightWallet::unsafe_from_buffer_regtest(include_bytes!(
                    "examples/regtest/aadaalacaadaalacaadaalac/orch_and_sapl/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Regtest(ExampleRegtestWalletSeed::AADAALACAADAALACAADAALAC(
                ExampleAADAALACAADAALACAADAALACVersion::OrchOnly,
            )) => {
                LightWallet::unsafe_from_buffer_regtest(include_bytes!(
                    "examples/regtest/aadaalacaadaalacaadaalac/orch_only/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::CBBHRWIILGBRABABSSHSMTPR(
                ExampleCBBHRWIILGBRABABSSHSMTPRVersion::V26,
            )) => {
                LightWallet::unsafe_from_buffer_testnet(include_bytes!(
                    "examples/testnet/cbbhrwiilgbrababsshsmtpr/v26/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::CBBHRWIILGBRABABSSHSMTPR(
                ExampleCBBHRWIILGBRABABSSHSMTPRVersion::V27,
            )) => {
                LightWallet::unsafe_from_buffer_testnet(include_bytes!(
                    "examples/testnet/cbbhrwiilgbrababsshsmtpr/v27/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::CBBHRWIILGBRABABSSHSMTPR(
                ExampleCBBHRWIILGBRABABSSHSMTPRVersion::V28,
            )) => {
                LightWallet::unsafe_from_buffer_testnet(include_bytes!(
                    "examples/testnet/cbbhrwiilgbrababsshsmtpr/v28/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::CBBHRWIILGBRABABSSHSMTPR(
                ExampleCBBHRWIILGBRABABSSHSMTPRVersion::G2f3830058,
            )) => {
                LightWallet::unsafe_from_buffer_testnet(include_bytes!(
                    "examples/testnet/cbbhrwiilgbrababsshsmtpr/G2f3830058/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::MSKMGDBHOTBPETCJWCSPGOPP(
                ExampleMSKMGDBHOTBPETCJWCSPGOPPVersion::Gab72a38b,
            )) => {
                LightWallet::unsafe_from_buffer_testnet(include_bytes!(
                    "examples/testnet/mskmgdbhotbpetcjwcspgopp/Gab72a38b/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::MSKMGDBHOTBPETCJWCSPGOPP(
                ExampleMSKMGDBHOTBPETCJWCSPGOPPVersion::G93738061a,
            )) => {
                LightWallet::unsafe_from_buffer_testnet(include_bytes!(
                    "examples/testnet/mskmgdbhotbpetcjwcspgopp/G93738061a/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::MSKMGDBHOTBPETCJWCSPGOPP(
                ExampleMSKMGDBHOTBPETCJWCSPGOPPVersion::Ga74fed621,
            )) => {
                LightWallet::unsafe_from_buffer_testnet(include_bytes!(
                    "examples/testnet/mskmgdbhotbpetcjwcspgopp/Ga74fed621/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Mainnet(ExampleMainnetWalletSeed::VTFCORFBCBPCTCFUPMEGMWBP(
                ExampleVTFCORFBCBPCTCFUPMEGMWBPVersion::V28,
            )) => {
                LightWallet::unsafe_from_buffer_mainnet(include_bytes!(
                    "examples/mainnet/vtfcorfbcbpctcfupmegmwbp/v28/zingo-wallet.dat"
                ))
                .await
            }
            ExampleWalletNetwork::Mainnet(ExampleMainnetWalletSeed::HHCCLALTPCCKCSSLPCNETBLR(
                ExampleHHCCLALTPCCKCSSLPCNETBLRVersion::Gf0aaf9347,
            )) => {
                LightWallet::unsafe_from_buffer_mainnet(include_bytes!(
                    "examples/mainnet/hhcclaltpcckcsslpcnetblr/gf0aaf9347/zingo-wallet.dat"
                ))
                .await
            }
        }
    }
    /// picks the seed (or ufvk) string associated with an example wallet
    pub async fn example_wallet_base(&self) -> String {
        match self {
            ExampleWalletNetwork::Regtest(ExampleRegtestWalletSeed::HMVASMUVWMSSVICHCARBPOCT(
                _,
            )) => crate::testvectors::seeds::HOSPITAL_MUSEUM_SEED.to_string(),
            ExampleWalletNetwork::Regtest(ExampleRegtestWalletSeed::AAAAAAAAAAAAAAAAAAAAAAAA(
                _,
            )) => crate::testvectors::seeds::ABANDON_ART_SEED.to_string(),
            ExampleWalletNetwork::Regtest(ExampleRegtestWalletSeed::AADAALACAADAALACAADAALAC(
                _,
            )) => "absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter advice comic".to_string(),
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::CBBHRWIILGBRABABSSHSMTPR(
                _,
            )) => crate::testvectors::seeds::CHIMNEY_BETTER_SEED.to_string(),
            ExampleWalletNetwork::Testnet(ExampleTestnetWalletSeed::MSKMGDBHOTBPETCJWCSPGOPP(
                _,
            )) => "mobile shuffle keen mother globe desk bless hub oil town begin potato explain table crawl just wild click spring pottery gasp often pill plug".to_string(),
            ExampleWalletNetwork::Mainnet(ExampleMainnetWalletSeed::VTFCORFBCBPCTCFUPMEGMWBP(
                _,
            )) => "village target fun course orange release female brain cruise birth pet copy trouble common fitness unfold panther man enjoy genuine merry write bulb pledge".to_string(),
            ExampleWalletNetwork::Mainnet(ExampleMainnetWalletSeed::HHCCLALTPCCKCSSLPCNETBLR(
                _,
            )) => "hotel humor crunch crack language awkward lunar term priority critic cushion keep coin sketch soap laugh pretty cement noodle enjoy trip bicycle list return".to_string(),
        }
    }
}
