[package]
name = "zingo-cli"
version = "0.2.0"
edition = "2024"

[dependencies]
zingolib = { workspace = true, features = [ "test-elevation" ] }
pepper-sync = { workspace = true }

clap = { workspace = true }
http = { workspace = true }

json = { workspace = true }
log = { workspace = true }
rustyline = { workspace = true }
shellwords = { workspace = true }

rustls.workspace = true

tracing-subscriber.workspace = true
