name: CI (Nightly)

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  build-test-artifacts:
    name: Build test artifacts
    runs-on: ubuntu-22.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build and archive tests
        run: cargo nextest archive --verbose --workspace --all-features --archive-file nextest-archive.tar.zst

      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          name: nextest-archive
          path: nextest-archive.tar.zst

  create-timestamp:
    uses: zingolabs/zingo-mobile/.github/workflows/create-timestamp.yaml@dev

  create-cache-key:
    uses: zingolabs/zingo-mobile/.github/workflows/create-cache-key.yaml@dev

  build-android:
    strategy:
      matrix:
        arch: [ x86_64, x86, arm64-v8a, armeabi-v7a ]
      fail-fast: false
    uses: zingolabs/zingo-mobile/.github/workflows/build.yaml@dev
    needs: create-cache-key
    with:
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      arch: ${{ matrix.arch }}

  integration-test-android:
    strategy:
      matrix:
        abi: [ x86_64, x86, arm64-v8a, armeabi-v7a ]
      fail-fast: false
    uses: zingolabs/zingo-mobile/.github/workflows/integration-test.yaml@dev
    needs: [ create-timestamp, create-cache-key, build-android ]
    with:
      timestamp: ${{ needs.create-timestamp.outputs.timestamp }}
      cache-key: ${{ needs.create-cache-key.outputs.cache-key }}
      abi: ${{ matrix.abi }}

