name: Coverage (Weekly)

on:
  schedule:
    - cron: "30 8 * * 0"
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: -D warnings
    container:
      image: zingodevops/ci-build:009
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.78

      - name: Install system deps
        run: |
          apt-get update
          apt-get install -y libsqlite3-dev pkg-config

      - name: create binaries dir
        run: mkdir -p ./test_binaries/bins

      - name: Symlink lightwalletd and zcash binaries
        run: ln -s /usr/bin/lightwalletd /usr/bin/zcashd /usr/bin/zcash-cli ./test_binaries/bins/

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Generate code coverage
        run: cargo llvm-cov nextest --workspace --lcov --output-path lcov.info

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: true
