[package]
name = "rustlib"
version = "1.0.1"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2021"

[dependencies]
zingolib = { workspace = true }
zingoconfig = { workspace = true }
lazy_static = "1.4.0"
base64 = "0.11.0"
